import ReversoSupportedLanguagesLib from 'reverso-api/src/enums/languages';

export enum GoogleSupportedLanguages {
  Afrikaans = 'af',
  Albanian = 'sq',
  Amharic = 'am',
  Arabic = 'ar',
  Armenian = 'hy',
  Assamese = 'as',
  Aymara = 'ay',
  Azerbaijani = 'az',
  Bambara = 'bm',
  Basque = 'eu',
  Belarusian = 'be',
  Bengali = 'bn',
  Bhojpuri = 'bho',
  Bosnian = 'bs',
  Bulgarian = 'bg',
  Catalan = 'ca',
  Cebuano = 'ceb',
  Chinese = 'zh',
  Corsican = 'co',
  Croatian = 'hr',
  Czech = 'cs',
  Danish = 'da',
  Dhivehi = 'dv',
  Dogri = 'doi',
  Dutch = 'nl',
  English = 'en',
  Esperanto = 'eo',
  Estonian = 'et',
  Ewe = 'ee',
  Finnish = 'fi',
  French = 'fr',
  Frisian = 'fy',
  Galician = 'gl',
  Georgian = 'ka',
  German = 'de',
  Greek = 'el',
  Guarani = 'gn',
  Gujarati = 'gu',
  Hausa = 'ha',
  Hawaiian = 'haw',
  Hebrew = 'he',
  Hindi = 'hi',
  Hmong = 'hmn',
  Hungarian = 'hu',
  Icelandic = 'is',
  Igbo = 'ig',
  Ilocano = 'ilo',
  Indonesian = 'id',
  Irish = 'ga',
  Italian = 'it',
  Japanese = 'ja',
  Javanese = 'jv',
  Kannada = 'kn',
  Kazakh = 'kk',
  Khmer = 'km',
  Kinyarwanda = 'rw',
  Konkani = 'gom',
  Korean = 'ko',
  Krio = 'kri',
  Kurdish = 'ku',
  Kyrgyz = 'ky',
  Lao = 'lo',
  Latin = 'la',
  Latvian = 'lv',
  Lingala = 'ln',
  Lithuanian = 'lt',
  Luganda = 'lg',
  Luxembourgish = 'lb',
  Macedonian = 'mk',
  Maithili = 'mai',
  Malagasy = 'mg',
  Malay = 'ms',
  Malayalam = 'ml',
  Maltese = 'mt',
  Maori = 'mi',
  Marathi = 'mr',
  Mizo = 'lus',
  Mongolian = 'mn',
  Nepali = 'ne',
  Norwegian = 'no',
  Oromo = 'om',
  Pashto = 'ps',
  Persian = 'fa',
  Polish = 'pl',
  Punjabi = 'pa',
  Quechua = 'qu',
  Romanian = 'ro',
  Russian = 'ru',
  Samoan = 'sm',
  Sanskrit = 'sa',
  Sepedi = 'nso',
  Serbian = 'sr',
  Sesotho = 'st',
  Shona = 'sn',
  Sindhi = 'sd',
  Slovak = 'sk',
  Slovenian = 'sl',
  Somali = 'so',
  Spanish = 'es',
  Sundanese = 'su',
  Swahili = 'sw',
  Swedish = 'sv',
  Tajik = 'tg',
  Tamil = 'ta',
  Tatar = 'tt',
  Telugu = 'te',
  Thai = 'th',
  Tigrinya = 'ti',
  Tsonga = 'ts',
  Turkish = 'tr',
  Turkmen = 'tk',
  Ukrainian = 'uk',
  Urdu = 'ur',
  Uyghur = 'ug',
  Uzbek = 'uz',
  Vietnamese = 'vi',
  Welsh = 'cy',
  Xhosa = 'xh',
  Yiddish = 'yi',
  Yoruba = 'yo',
  Zulu = 'zu',
  Portuguese = 'pt',
}

export enum AppSupportedLanguages {
  ARABIC = 'arabic',
  GERMAN = 'german',
  SPANISH = 'spanish',
  FRENCH = 'french',
  HEBREW = 'hebrew',
  ITALIAN = 'italian',
  JAPANESE = 'japanese',
  DUTCH = 'dutch',
  POLISH = 'polish',
  PORTUGUESE = 'portuguese',
  ROMANIAN = 'romanian',
  RUSSIAN = 'russian',
  TURKISH = 'turkish',
  CHINESE = 'chinese',
  ENGLISH = 'english',
  UKRAINIAN = 'ukrainian',
}

export const SupportedLanguagesToI18nMap: Record<
  AppSupportedLanguages,
  GoogleSupportedLanguages
> = {
  [AppSupportedLanguages.ARABIC]: GoogleSupportedLanguages.Arabic,
  [AppSupportedLanguages.ENGLISH]: GoogleSupportedLanguages.English,
  [AppSupportedLanguages.GERMAN]: GoogleSupportedLanguages.German,
  [AppSupportedLanguages.SPANISH]: GoogleSupportedLanguages.Spanish,
  [AppSupportedLanguages.FRENCH]: GoogleSupportedLanguages.French,
  [AppSupportedLanguages.HEBREW]: GoogleSupportedLanguages.Hebrew,
  [AppSupportedLanguages.ITALIAN]: GoogleSupportedLanguages.Italian,
  [AppSupportedLanguages.JAPANESE]: GoogleSupportedLanguages.Japanese,
  [AppSupportedLanguages.DUTCH]: GoogleSupportedLanguages.Dutch,
  [AppSupportedLanguages.POLISH]: GoogleSupportedLanguages.Polish,
  [AppSupportedLanguages.PORTUGUESE]: GoogleSupportedLanguages.Portuguese,
  [AppSupportedLanguages.ROMANIAN]: GoogleSupportedLanguages.Romanian,
  [AppSupportedLanguages.RUSSIAN]: GoogleSupportedLanguages.Russian,
  [AppSupportedLanguages.TURKISH]: GoogleSupportedLanguages.Turkish,
  [AppSupportedLanguages.UKRAINIAN]: GoogleSupportedLanguages.Ukrainian,
  [AppSupportedLanguages.CHINESE]: GoogleSupportedLanguages.Chinese,
};

export const ReversoSupportedLanguages = ReversoSupportedLanguagesLib;
export const LANGUAGE_LIST = Object.entries(AppSupportedLanguages);
export const LANGUAGE_FLAGS: Record<AppSupportedLanguages, string> = {
  english: '🇬🇧',
  spanish: '🇪🇸',
  french: '🇫🇷',
  german: '🇩🇪',
  italian: '🇮🇹',
  portuguese: '🇧🇷',
  russian: '🇷🇺',
  chinese: '🇨🇳',
  japanese: '🇯🇵',
  arabic: '🇸🇦',
  turkish: '🇹🇷',
  dutch: '🇳🇱',
  hebrew: '🇮🇱',
  polish: '🇵🇱',
  romanian: '🇷🇴',
  ukrainian: '🇺🇦',
} as const;
